---

- hosts: test-servers
  become: true
  tasks:
    - name: install nginx
      yum: pkg=nginx state=installed
      sudo: yes
      notify:
        - start nginx
  handlers:
    - name: start nginx
      service: name=nginx state=started